sudo: required
language: python
services:
- docker

before_install:
- docker run --name=redis-unicron -d redis:alpine
- docker build -t unicron-test -f ./Dockerfile.tests .
- docker run --name=unicron-test --link=redis-unicron -e "UNICRON_KEY=xxxxxxxxxxxxxxxx"
  -e "TZ=Europe/Amsterdam" -e "REDIS_HOST=redis-unicron" unicron-test

install:
- docker build -t layzeelab/unicron -f ./Dockerfile .
- docker run --name=unicron --link=redis-unicron -p 8185:80 -e "UNICRON_KEY=xxxxxxxxxxxxxxxx"
  -e "TZ=Europe/Amsterdam" -e "REDIS_HOST=redis-unicron" -d layzeelab/unicron
- docker ps -a

script:
- curl --silent http://localhost:8185/api/ | grep Unicron

deploy:
  provider: script
  script: bash run_push.sh
  on:
    branch: master

notifications:
  slack:
    on_pull_requests: false
    secure: NSiQoy8rcLgtOXghEETCnlbkpcXSmvvTME4HwsXILJ0AuoMJeCqrA9dS3f8fKQwxhjirN/P/rprwXLk6wfEt8aPCBn+TckRB5/gqVfOze1VZT7Kwi3ZIIuiNWcI+XzEhxKfPpbBVZqJS11fcVYc3FiOLm15pN8rWsJbu9QQ2wrPCDCR3Qx2TNcpMHFBqm02jIsbbtV6iWNW7EpJhiisxfmAIfMZVtZ2YH5naUega80pJZKQlGv7poq7aFJ5HeuI9GpiNp+LjrYVaQL7v8Hq8B/y+35sn4lvTtFjVPvh0cj0yjIhHdjxhGfFsP6W3GSyrf5DgLoHxuBPcEsxNMbhjvD0JGEGqrSEzfB8LoA0c9KoCklP2ubrKDRXljRKiR3xfbWMWJl/XAo6nYEQ+kDpMmd8pEEgfGYEX989S4aJiX/2aBb0FK4I2lug7bhGZk5/BN1Mn1TPby++JOKupoQGcl+MP84wReYWrLyDbNMpJAunUjW/+UE2kJ7eSrji1mUrXZyNmXSu0bGbXt8BkD6vPoehPTgxTVFagJG8rm49x/egjnR7ekhHA+F+WGuYcinWUUx+feRlvh+vXHRWsYZ1SMVnhmKUgST7+eUABUeHOoNQDmG4pFo16F4CMa9C5RZcjoMbZdJ/gz0wUsJ9ADAM2oF02AIx3pLNqaMQE8uFdkh8=
