#!/bin/sh
# (c) layzeelab.com 2018, Armin Ranjbar Daemi (@rmin)
#
# This file is part of Unicron (@layzeelab).
# Unicron is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

WORKER=www-data
mkdir /run/uwsgi/
chown $WORKER /run/uwsgi/
exec uwsgi --socket /run/uwsgi/app.sock --wsgi-file /var/unicron/api.py --callable app \
	--master --processes 4 --threads 2 --uid $WORKER --disable-logging > /dev/null 2>&1